engines:
  shellcheck:
    enabled: true
    checks:
      SC1091:
        enabled: false
  markdownlint:
    enabled: true
    checks:
      MD009:
        enabled: false
      MD013:
        enabled: false
      MD036:
        enabled: false
ratings:
   paths:
   - "**.sh"
   - "**.md"
