language: generic
sudo: true

script:
    - wget http://ftp.gnu.org/gnu/wget/wget-1.18.tar.xz
    - tar xf wget-1.18.tar.xz
    - cd wget-1.18
    - ./configure
    - make
    - sudo make install
    - cd ..
    - set -e
    - ./clean.sh
    - ./update.sh
    - ./build.sh
    - sudo ./buildroot.sh
    - set +e

addons:
    apt:
        packages:
            - git
            - curl
            - bzip2
            - zip
            - xz-utils
            - gnupg
            - kpartx
            - dosfstools
            - binutils
            - bc

